[versions]
accompanistDrawablepainter = "0.37.3"
accompanistSwiperefresh = "0.36.0"
agp = "8.13.0"
annotation = "1.9.1"
anrwatchdog = "1.4.0"
appcompat = "1.7.1"
browser = "1.9.0"
bsh = "3.0.0-SNAPSHOT"
collection = "1.5.0"
commonsNet = "3.12.0"
constraintlayoutCompose = "1.1.1"
datastorePreferences = "1.1.2"
desugar_jdk_libs = "2.1.5"
eventbus = "3.3.1"
foundation = "1.9.1"
glide = "5.0.4"
kotlinReflect = "2.2.20"
ktsh = "1.0.0"
leakcanaryAndroid = "2.14"
library = "1.1.6"
material = "1.13.0"
constraintlayout = "2.2.0"
material3 = "1.4.0-alpha08"
media3Exoplayer = "1.8.0"
media3ExoplayerDash = "1.5.1"
media3Ui = "1.8.0"
modernandroidpreferences = "2.4.0-beta1"
nanohttpd = "2.3.1"
navigationFragment = "2.9.4"
navigationUi = "2.8.7"
kotlin = "2.2.20"
asynclayoutinflater = "1.1.0"
navigationFragmentKtx = "2.8.7"
navigationUiKtx = "2.9.4"
coreKtx = "1.13.1"
activity = "1.11.0"
nbJavacAndroid = "17.0.0.3"
okhttp = "5.1.0"
orgEclipseJgit = "6.2.0.202206071550-r"
photoview = "2.3.0"
quickjsAndroid = "0.9.2"
composeRuntime = "1.9.0"
sshj = "0.40.0"
swiperefreshlayout = "1.1.0"
terminalView = "0.118.3"
kotlinPlugin = "2.2.20"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.6.1"
coordinatorlayout = "1.3.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.9.3"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.11.0"
composeBom = "2025.09.00"
coilCompose = "2.7.0"
navigationCompose = "2.9.4"
lifecycleViewmodelAndroid = "2.8.7"
wordWrap = "0.1.13"
coreAnimation = "1.0.0"
runtimeAndroid = "1.9.1"

tsBinding = "4.3.1"
lsp4j = "0.24.0"
androidxAnnotation = "1.9.1"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
baselineprofile = "1.4.1"
profileinstaller = "1.4.1"
benchmark = "1.2.4"
runner = "1.5.2"
benchmarkJunit4 = "1.2.4"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistDrawablepainter" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeRuntime" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
anrwatchdog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anrwatchdog" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
bsh = { module = "org.beanshell:bsh", version.ref = "bsh" }
collection = { module = "androidx.collection:collection", version.ref = "collection" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
ktsh = { module = "com.jaredrummler:ktsh", version.ref = "ktsh" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
library = { module = "me.zhanghai.android.libarchive:library", version.ref = "library" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3ExoplayerDash" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
asynclayoutinflater = { group = "androidx.asynclayoutinflater", name = "asynclayoutinflater", version.ref = "asynclayoutinflater" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
#lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
nb-javac-android = { module = "io.github.itsaky:nb-javac-android", version.ref = "nbJavacAndroid" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
org-eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "orgEclipseJgit" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
quickjs-android = { module = "app.cash.quickjs:quickjs-android", version.ref = "quickjsAndroid" }
sshj = { module = "com.hierynomus:sshj", version.ref = "sshj" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.10.1" }
terminal-view = { group = "com.termux.termux-app", name = "terminal-view", version.ref = "terminalView" }
terminal-emulator = { group = "com.termux.termux-app", name = "terminal-emulator", version.ref = "terminalView" }
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }
#jcodings = { module = "org.jruby.jcodings:jcodings", version = "1.0.61" }
#joni = { module = "org.jruby.joni:joni", version = "2.2.3" }
#snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version = "2.9" }
#jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.4.0" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material-compose = { group = "androidx.compose.material", name = "material", version = "1.9.1" }
material3 = { group = "androidx.compose.material3", name = "material3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
material-motion-compose-core = { group = "io.github.fornewid", name = "material-motion-compose-core", version = "2.0.1" }
lifecycle-viewmodel-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-android", version.ref = "lifecycleViewmodelAndroid" }
word-wrap = { module = "com.github.davidmoten:word-wrap", version.ref = "wordWrap" }
core-animation = { group = "androidx.core", name = "core-animation", version.ref = "coreAnimation" }
runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }


androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-collection = { module = "androidx.collection:collection", version = "1.5.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.6.1" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }
#kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.10.2" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.3" }
#material = { module = "com.google.android.material:material", version = "1.12.0" }
tree-sitter-java = { module = "com.itsaky.androidide.treesitter:tree-sitter-java", version.ref = "tsBinding" }
tree-sitter = { module = "com.itsaky.androidide.treesitter:android-tree-sitter", version.ref = "tsBinding" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
junit = { module = "junit:junit", version = "4.13.2" }
#gson = { module = "com.google.code.gson:gson", version = "2.13.1" }
jcodings = { module = "org.jruby.jcodings:jcodings", version = "1.0.63" }
joni = { module = "org.jruby.joni:joni", version = "2.2.6" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version = "2.10" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.15.2" }
jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.3.100" }
monarch-code = { module = "io.github.dingyi222666.monarch:monarch", version = "1.0.3" }
monarch-language-pack = { module = "io.github.dingyi222666.monarch:monarch-language-pack", version = "1.0.2" }
monarch-json = { module = "io.github.dingyi222666.monarch:monarch-json-loader", version = "1.0.2" }
regex-onig = { module = "io.github.dingyi222666.regex-lib:regex-lib-oniguruma", version = "1.0.3" }
regex-re2j = { module = "io.github.dingyi222666.regex-lib:regex-lib-re2j", version = "1.0.2" }

tests-google-truth = { module = "com.google.truth:truth", version = "1.4.4" }
tests-robolectric = { module = "org.robolectric:robolectric", version = "4.16" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "benchmarkJunit4" }



[plugins]

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"  }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlinPlugin"  }

kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish.base", version = "0.34.0" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }

