[versions]
agp = "8.13.1"
annotation = "1.9.1"
anrwatchdog = "1.4.0"
appcompat = "1.7.1"
browser = "1.9.0"
commonsNet = "3.12.0"
coreVersion = "0.3.0"
desugar_jdk_libs = "2.1.5"
documentfile = "1.1.0"
glide = "5.0.5"
kotlinReflect = "2.2.20"
material = "1.13.0"
constraintlayout = "2.2.1"
materialIconsCore = "1.7.8"
media3Ui = "1.8.0"
nanohttpd = "2.3.1"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
kotlin = "2.2.21"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
coreKtx = "1.17.0"
activity = "1.12.0"
okhttp = "5.3.2"
photoview = "2.3.0"
quickjsAndroid = "0.9.2"
composeRuntime = "1.10.0"
kotlinPlugin = "2.2.21"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleViewmodelKtx = "2.10.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
coilCompose = "2.7.0"
navigationCompose = "2.9.6"
ktfmt = "0.25.0"

tsBinding = "4.3.1"
lsp4j = "0.24.0"
androidxAnnotation = "1.9.1"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
baselineprofile = "1.4.1"
profileinstaller = "1.4.1"
benchmark = "1.4.1"
runner = "1.7.0"
benchmarkJunit4 = "1.4.1"
lifecycleProcess = "2.10.0"
composeDnd = "0.4.0"
androidsvgAar = "1.4"

[libraries]
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeRuntime" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
anrwatchdog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anrwatchdog" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
pine-core = { module = "top.canyie.pine:core", version.ref = "coreVersion" }
quickjs-android = { module = "app.cash.quickjs:quickjs-android", version.ref = "quickjsAndroid" }
utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.10.2" }
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
material3 = { group = "androidx.compose.material3", name = "material3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
material-motion-compose-core = { group = "io.github.fornewid", name = "material-motion-compose-core", version = "2.0.1" }
compose-dnd = { module = "com.mohamedrejeb.dnd:compose-dnd", version.ref = "composeDnd" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-collection = { module = "androidx.collection:collection", version = "1.5.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.3" }
tree-sitter-java = { module = "com.itsaky.androidide.treesitter:tree-sitter-java", version.ref = "tsBinding" }
tree-sitter = { module = "com.itsaky.androidide.treesitter:android-tree-sitter", version.ref = "tsBinding" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
junit = { module = "junit:junit", version = "4.13.2" }
jcodings = { module = "org.jruby.jcodings:jcodings", version = "1.0.63" }
joni = { module = "org.jruby.joni:joni", version = "2.2.6" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version = "2.10" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.15.2" }
jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.3.100" }
monarch-code = { module = "io.github.dingyi222666.monarch:monarch", version = "1.0.3" }
monarch-language-pack = { module = "io.github.dingyi222666.monarch:monarch-language-pack", version = "1.0.2" }
monarch-json = { module = "io.github.dingyi222666.monarch:monarch-json-loader", version = "1.0.2" }
regex-onig = { module = "io.github.dingyi222666.regex-lib:regex-lib-oniguruma", version = "1.0.3" }
regex-re2j = { module = "io.github.dingyi222666.regex-lib:regex-lib-re2j", version = "1.0.2" }

tests-google-truth = { module = "com.google.truth:truth", version = "1.4.5" }
tests-robolectric = { module = "org.robolectric:robolectric", version = "4.16" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "benchmarkJunit4" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
androidsvg-aar = { group = "com.caverock", name = "androidsvg-aar", version.ref = "androidsvgAar" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"  }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlinPlugin"  }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }

publish = { id = "com.vanniktech.maven.publish.base", version = "0.34.0" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }

