[versions]
accompanistSwiperefresh = "0.36.0"
agp = "8.6.0"
annotation = "1.9.1"
anrwatchdog = "1.4.0"
appcompat = "1.7.0"
browser = "1.8.0"
bsh = "3.0.0-SNAPSHOT"
collection = "1.4.5"
commonsNet = "3.11.1"
datastorePreferences = "1.1.2"
desugar_jdk_libs = "2.1.5"
eventbus = "3.3.1"
foundation = "1.8.0-beta02"
glide = "4.16.0"
ktsh = "1.0.0"
leakcanaryAndroid = "2.14"
lsp4j = "0.24.0"
material = "1.12.0"
constraintlayout = "2.2.0"
material3 = "1.4.0-alpha08"
media3Exoplayer = "1.5.1"
media3ExoplayerDash = "1.5.1"
media3Ui = "1.5.1"
modernandroidpreferences = "2.4.0-beta1"
nanohttpd = "2.3.1"
navigationFragment = "2.8.7"
navigationUi = "2.8.7"
kotlin = "2.1.10"
asynclayoutinflater = "1.0.0"
navigationFragmentKtx = "2.8.7"
navigationUiKtx = "2.8.5"
coreKtx = "1.13.1"
activity = "1.10.0"
nbJavacAndroid = "17.0.0.3"
okhttp = "4.12.0"
orgEclipseJgit = "6.2.0.202206071550-r"
photoview = "2.3.0"
quickjsAndroid = "0.9.2"
sshj = "0.39.0"
swiperefreshlayout = "1.1.0"
terminalView = "0.118.1"
kotlinPlugin = "2.1.10"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
coordinatorlayout = "1.2.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
composeBom = "2025.02.00"
coilCompose = "2.7.0"
navigationCompose = "2.8.7"
lifecycleViewmodelAndroid = "2.8.7"
wordWrap = "0.1.13"
coreAnimation = "1.0.0"
runtimeAndroid = "1.7.8"

[libraries]
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
anrwatchdog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anrwatchdog" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
bsh = { module = "org.beanshell:bsh", version.ref = "bsh" }
collection = { module = "androidx.collection:collection", version.ref = "collection" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
ktsh = { module = "com.jaredrummler:ktsh", version.ref = "ktsh" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3ExoplayerDash" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
asynclayoutinflater = { group = "androidx.asynclayoutinflater", name = "asynclayoutinflater", version.ref = "asynclayoutinflater" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
nb-javac-android = { module = "io.github.itsaky:nb-javac-android", version.ref = "nbJavacAndroid" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
org-eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "orgEclipseJgit" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
quickjs-android = { module = "app.cash.quickjs:quickjs-android", version.ref = "quickjsAndroid" }
sshj = { module = "com.hierynomus:sshj", version.ref = "sshj" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.10.1" }
terminal-view = {group = "com.github.termux.termux-app", name = "terminal-view", version.ref = "terminalView" }
terminal-emulator = { group = "com.github.termux.termux-app", name = "terminal-emulator", version.ref = "terminalView" }
gson = { module = "com.google.code.gson:gson", version = "2.12.1" }
jcodings = { module = "org.jruby.jcodings:jcodings", version = "1.0.61" }
joni = { module = "org.jruby.joni:joni", version = "2.2.3" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version = "2.9" }
jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.3.100" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material-compose = { group = "androidx.compose.material", name = "material", version = "1.7.8" }
material3 = { group = "androidx.compose.material3", name = "material3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
material-motion-compose-core = { group = "io.github.fornewid", name = "material-motion-compose-core", version = "2.0.1" }
lifecycle-viewmodel-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-android", version.ref = "lifecycleViewmodelAndroid" }
word-wrap = { module = "com.github.davidmoten:word-wrap", version.ref = "wordWrap" }
core-animation = { group = "androidx.core", name = "core-animation", version.ref = "coreAnimation" }
runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
[plugins]

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"  }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlinPlugin"  }
